import streamlit as st
import pandas as pd
import plotly.express as px
import os

st.set_page_config(page_title="Job Market Analytics Dashboard", page_icon="📊", layout="wide")

st.title("📊 Developer Job Market Analytics Dashboard")
st.markdown("This dashboard reads local CSV files generated by your data pipeline to track software market insights.")

if not os.path.exists("cleaned_jobs.csv"):
    st.error("⚠️ Cleaned data file not found! Please run 'pipeline.py' first.")
else:
    df = pd.read_csv("cleaned_jobs.csv")

    st.sidebar.header("🛠️ Dashboard Controls")
    search_query = st.sidebar.text_input("Search Job Titles (e.g., Python):", "")
    
    if search_query:
        df = df[df['title'].str.contains(search_query, case=False, na=False)]

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Total Jobs Tracked", len(df))
    with col2:
        st.metric("Unique Employers", df['company'].nunique())
    with col3:
        st.metric("Hiring Cities", df['city'].nunique())

    st.markdown("---")

    graph_col1, graph_col2 = st.columns(2)

    with graph_col1:
        st.subheader("🏢 Top Hiring Companies")
        company_counts = df['company'].value_counts().head(10).reset_index()
        company_counts.columns = ['Company', 'Job Postings']
        fig_company = px.bar(company_counts, x='Job Postings', y='Company', orientation='h',
                             color='Job Postings', color_continuous_scale='viridis')
        st.plotly_chart(fig_company, use_container_width=True)

    with graph_col2:
        st.subheader("📍 Job Distribution by City")
        location_counts = df['city'].value_counts().head(10).reset_index()
        location_counts.columns = ['City Location', 'Job Count']
        fig_loc = px.pie(location_counts, values='Job Count', names='City Location', hole=0.3)
        st.plotly_chart(fig_loc, use_container_width=True)

    st.subheader("🔍 Explore Available Jobs Dataset")
    st.dataframe(df[['title', 'company', 'location', 'date_scraped']], use_container_width=True)
